[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis","@supabase/supabase-js"]

# optional: run a scheduled job later
# [functions."gmail-sync"]
#   schedule = "@hourly"

[functions."gmail-sync"]
  schedule = "@hourly"   # or "0 3 * * *" for daily at 3am UTC
