# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Use esbuild bundler and tell Netlify to include heavy external libs
  node_bundler = "esbuild"
  external_node_modules = ["googleapis", "cheerio", "@supabase/supabase-js"]

  # Ensure we’re on a modern Node runtime
  included_files = ["netlify/functions/**"]

[build.environment]
  NODE_VERSION = "20"

# Give gmail-sync extra headroom for slow Gmail API calls
[functions."gmail-sync"]
  timeout = 26
  memory = 512
